//! Prometheus metrics exposition
//!
//! Defines and tracks key performance metrics.

use lazy_static::lazy_static;
use prometheus::{
    register_counter_vec, register_histogram_vec, register_int_gauge, CounterVec, HistogramVec,
    IntGauge,
};

lazy_static! {
    /// Total HTTP requests processed
    pub static ref HTTP_REQUESTS_TOTAL: CounterVec = register_counter_vec!(
        "websec_http_requests_total",
        "Total number of HTTP requests processed",
        &["decision"] // ALLOW, RATE_LIMIT, CHALLENGE, BLOCK
    )
    .unwrap();

    /// Request processing latency
    pub static ref REQUEST_DURATION_SECONDS: HistogramVec = register_histogram_vec!(
        "websec_request_duration_seconds",
        "HTTP request processing duration in seconds",
        &["decision"],
        vec![0.001, 0.005, 0.010, 0.025, 0.050, 0.100, 0.250, 0.500, 1.0]
    )
    .unwrap();

    /// Signals generated by detector
    pub static ref SIGNALS_GENERATED_TOTAL: CounterVec = register_counter_vec!(
        "websec_signals_generated_total",
        "Total signals generated by detectors",
        &["detector", "signal_type"]
    )
    .unwrap();

    /// Current reputation score distribution
    pub static ref REPUTATION_SCORE_BUCKET: CounterVec = register_counter_vec!(
        "websec_reputation_score_bucket",
        "Distribution of reputation scores",
        &["bucket"] // 0-20, 20-40, 40-70, 70-100
    )
    .unwrap();

    /// Currently tracked IPs
    pub static ref TRACKED_IPS_TOTAL: IntGauge = register_int_gauge!(
        "websec_tracked_ips_total",
        "Total number of IPs currently being tracked"
    )
    .unwrap();

    /// Storage backend health
    pub static ref STORAGE_HEALTH: IntGauge = register_int_gauge!(
        "websec_storage_health",
        "Storage backend health (1 = healthy, 0 = unhealthy)"
    )
    .unwrap();
}

/// Record a request decision
pub fn record_request_decision(decision: &str, duration: f64) {
    HTTP_REQUESTS_TOTAL.with_label_values(&[decision]).inc();
    REQUEST_DURATION_SECONDS
        .with_label_values(&[decision])
        .observe(duration);
}

/// Record a signal generation
pub fn record_signal(detector: &str, signal_type: &str) {
    SIGNALS_GENERATED_TOTAL
        .with_label_values(&[detector, signal_type])
        .inc();
}

/// Update reputation score bucket
pub fn update_score_bucket(score: u8) {
    let bucket = match score {
        0..=19 => "0-20",
        20..=39 => "20-40",
        40..=69 => "40-70",
        70..=100 => "70-100",
        _ => "unknown",
    };
    REPUTATION_SCORE_BUCKET.with_label_values(&[bucket]).inc();
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_record_request_decision() {
        record_request_decision("ALLOW", 0.005);
        // Verify it doesn't panic
    }

    #[test]
    fn test_record_signal() {
        record_signal("BotDetector", "SuspiciousUserAgent");
    }

    #[test]
    fn test_update_score_bucket() {
        update_score_bucket(100);
        update_score_bucket(75);
        update_score_bucket(50);
        update_score_bucket(25);
        update_score_bucket(10);
    }
}
