//! Detector trait definition
//!
//! Defines the Strategy pattern interface for all threat detectors.
//! Each detector analyzes HTTP requests and generates signals.

use crate::reputation::Signal;
use async_trait::async_trait;
use std::net::IpAddr;

/// HTTP request context for analysis
///
/// Contains all relevant information from an HTTP request needed
/// for threat detection.
#[derive(Debug, Clone)]
pub struct HttpRequestContext {
    /// Client IP address
    pub ip: IpAddr,
    /// HTTP method (GET, POST, etc.)
    pub method: String,
    /// Request path
    pub path: String,
    /// Query string (if present)
    pub query: Option<String>,
    /// HTTP headers (name -> value)
    pub headers: Vec<(String, String)>,
    /// Request body (for POST/PUT, limited size)
    pub body: Option<Vec<u8>>,
    /// User-Agent header (extracted for convenience)
    pub user_agent: Option<String>,
    /// Referer header (extracted for convenience)
    pub referer: Option<String>,
    /// Content-Type header
    pub content_type: Option<String>,
}

/// Result of detector analysis
#[derive(Debug)]
pub struct DetectionResult {
    /// Signals generated by this detector
    pub signals: Vec<Signal>,
    /// Whether the detector found suspicious activity
    pub suspicious: bool,
    /// Optional diagnostic message
    pub message: Option<String>,
}

impl DetectionResult {
    /// Create a clean result (no threats detected)
    #[must_use]
    pub fn clean() -> Self {
        Self {
            signals: Vec::new(),
            suspicious: false,
            message: None,
        }
    }

    /// Create a result with a single signal
    #[must_use]
    pub fn with_signal(signal: Signal) -> Self {
        Self {
            signals: vec![signal],
            suspicious: true,
            message: None,
        }
    }

    /// Create a result with multiple signals
    #[must_use]
    pub fn with_signals(signals: Vec<Signal>) -> Self {
        let suspicious = !signals.is_empty();
        Self {
            signals,
            suspicious,
            message: None,
        }
    }

    /// Add a message to the result
    #[must_use]
    pub fn with_message(mut self, message: String) -> Self {
        self.message = Some(message);
        self
    }
}

/// Threat detector trait
///
/// All detectors must implement this trait. Each detector is responsible
/// for analyzing one or more threat families (e.g., bot detection, SQL injection).
///
/// # Strategy Pattern
///
/// This trait enables the Strategy pattern, allowing detectors to be:
/// - Pluggable (easily add/remove detectors)
/// - Testable (mock implementations)
/// - Composable (combine multiple detectors)
#[async_trait]
pub trait Detector: Send + Sync {
    /// Get the detector name for logging/metrics
    fn name(&self) -> &str;

    /// Analyze an HTTP request for threats
    ///
    /// Returns a `DetectionResult` containing any signals generated.
    ///
    /// # Arguments
    ///
    /// * `context` - HTTP request context to analyze
    ///
    /// # Returns
    ///
    /// A `DetectionResult` with zero or more signals if threats detected.
    async fn analyze(&self, context: &HttpRequestContext) -> DetectionResult;

    /// Check if this detector is enabled
    ///
    /// Allows runtime enable/disable of detectors via configuration.
    fn enabled(&self) -> bool {
        true
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::reputation::SignalVariant;
    use std::str::FromStr;

    #[test]
    fn test_detection_result_clean() {
        let result = DetectionResult::clean();
        assert!(!result.suspicious);
        assert_eq!(result.signals.len(), 0);
    }

    #[test]
    fn test_detection_result_with_signal() {
        let signal = Signal::new(SignalVariant::FailedLogin);
        let result = DetectionResult::with_signal(signal);
        assert!(result.suspicious);
        assert_eq!(result.signals.len(), 1);
    }

    #[test]
    fn test_detection_result_with_message() {
        let result = DetectionResult::clean().with_message("Test message".to_string());
        assert_eq!(result.message.unwrap(), "Test message");
    }

    #[test]
    fn test_http_request_context() {
        let ip = IpAddr::from_str("192.168.1.1").unwrap();
        let context = HttpRequestContext {
            ip,
            method: "GET".to_string(),
            path: "/api/login".to_string(),
            query: Some("user=admin".to_string()),
            headers: vec![("User-Agent".to_string(), "curl/7.68.0".to_string())],
            body: None,
            user_agent: Some("curl/7.68.0".to_string()),
            referer: None,
            content_type: None,
        };

        assert_eq!(context.method, "GET");
        assert_eq!(context.path, "/api/login");
        assert!(context.user_agent.is_some());
    }

    // Mock detector for testing
    struct MockDetector {
        name: String,
        should_detect: bool,
    }

    #[async_trait]
    impl Detector for MockDetector {
        fn name(&self) -> &str {
            &self.name
        }

        async fn analyze(&self, _context: &HttpRequestContext) -> DetectionResult {
            if self.should_detect {
                DetectionResult::with_signal(Signal::new(SignalVariant::SuspiciousUserAgent))
                    .with_message("Mock detection".to_string())
            } else {
                DetectionResult::clean()
            }
        }
    }

    #[tokio::test]
    async fn test_mock_detector_clean() {
        let detector = MockDetector {
            name: "MockDetector".to_string(),
            should_detect: false,
        };

        let ip = IpAddr::from_str("192.168.1.1").unwrap();
        let context = HttpRequestContext {
            ip,
            method: "GET".to_string(),
            path: "/".to_string(),
            query: None,
            headers: vec![],
            body: None,
            user_agent: None,
            referer: None,
            content_type: None,
        };

        let result = detector.analyze(&context).await;
        assert!(!result.suspicious);
    }

    #[tokio::test]
    async fn test_mock_detector_suspicious() {
        let detector = MockDetector {
            name: "MockDetector".to_string(),
            should_detect: true,
        };

        let ip = IpAddr::from_str("192.168.1.1").unwrap();
        let context = HttpRequestContext {
            ip,
            method: "GET".to_string(),
            path: "/".to_string(),
            query: None,
            headers: vec![],
            body: None,
            user_agent: None,
            referer: None,
            content_type: None,
        };

        let result = detector.analyze(&context).await;
        assert!(result.suspicious);
        assert_eq!(result.signals.len(), 1);
        assert_eq!(result.message.unwrap(), "Mock detection");
    }
}
